### ISSUE TITLE
About the Project

### ISSUE THREAD

**Issue by dudil** [orsinium-labs/flitenv#1]
Hi @orsinium - 

I was exactly looking for a similar project and would like to ask you about it before setting up one myself.
Is the purpose of this project to use flit and its pyproject.toml support provided to install the requirements into a virtualenv?

Thanks,
Dudi

**Comment by orsinium** [comment]
Yes, this is a tool that creates venv for every extra and installs the dependencies in it. For example, if you have `dev` extras, the command `flitenv dev run flake8` will create venv `dev`, install main dependencies and dependencies from `dev` extra, and run `flake8` in the given venv. I'll update the readme soon.

**Comment by orsinium** [comment]
At the moment, I'm checking it "on production" in my organization. I'll drop a few simple tests soon as well.

**Comment by dudil** [comment]
Thanks - I was under the impression this is an alternative for pipenv using flit.
There were quite few discussion on that comment (https://github.com/pypa/pip/issues/8049)

If this is not the case here - sorry for the bother, I'll probably will set a new project and will think of another name than flitenv :-)
